### ISSUE TITLE
Remove Console Output

### ISSUE THREAD

**Issue by themetalone** [maybeec/oomph-task-unzip#12]
The console output is too large atm. There is one line per file and folder which floods the installer log while unzipping large files

**Comment by maybeec** [comment]
However, please be aware, that the user should get some response, that the installer is working and not idle. I totally agree, but I do not see any other good option, do you?

**Comment by themetalone** [comment]
I'll need to research a bit but maybe the used unarchive library allows to
count files or size and then I could output percentages in reasonable steps

Am 18.11.2016 8:11 vorm. schrieb "Malte Brunnlieb" <notifications@github.com

**Comment by themetalone** [comment]
Ok. Since the current unarchive api works on a stream of unknown size I see no possibility to reduce the output
