### ISSUE TITLE
MSI extraction fails if whitespace in path

### ISSUE THREAD

**Issue by maybeec** [maybeec/oomph-task-unzip#13]
If there is a whitespace in MSI file path, the extraction fails:

```
Execute: msiexec /a "I:\eclipse\Neuer Ordner\temp\nodejs.msi" /qn TARGETDIR="I:\eclipse\Neuer Ordner\software\nodejs\" @ I:\eclipse\Neuer Ordner
Performing cli install.nodejs.cleanup.msi
Execute: del "I:\eclipse\Neuer Ordner\software\nodejs\nodejs.msi" @ I:\eclipse\Neuer Ordner
I:\eclipse\Neuer Ordner\software\nodejs\nodejs.msi konnte nicht gefunden werden
```

**Comment by themetalone** [comment]
How is this related to the unzip task?

**Comment by maybeec** [comment]
sry... I was guessing, that this part of the unzip task. But you are right, hat is part of the profile.
Would it make sense to let the unzip task support msi?

**Comment by themetalone** [comment]
I can test if the apache commons compress library can handle it.

**Comment by maybeec** [comment]
I don't think so, there are some pitfalls with msi, so maybe we should not integrated it. Basically, whenever extracting an MSI it will waste your registry with additional garbage, which can be hardly circumvented. I tried it somehow without success. See eirslett/frontend-maven-plugin#490 and the comments on my PR as well as the upcoming issues in https://github.com/eirslett/frontend-maven-plugin/issues/503#issuecomment-258754636
