### ISSUE TITLE
Clean up ReadMe

### ISSUE THREAD

**Issue by OLibutzki** [maybeec/oomph-task-unzip#9]
The schema location (https://raw.githubusercontent.com/maybeec/oomph-task-unzip/master/task-unzip-updatesite/model/Task-unzip-1.0.ecore) mentioned in the readme returns a 404 error.

**Comment by themetalone** [comment]
The readme is pretty outdated. This is on top of my todo list right now.

take this one instead: https://github.com/maybeec/oomph-task-unzip/blob/master/task-unzip-updatesite/model/Oomph-task-unzip.ecore
